### ISSUE TITLE
JRE >=9 on OSX has deprecated key apple methods

### ISSUE THREAD

**Issue by majenkotech** [UECIDE/UECIDE#136]
java.lang.NoSuchMethodError: com.apple.eawt.Application.addApplicationListener(Lcom/apple/eawt/ApplicationListener;)V at org.uecide.macosx.ThinkDifferent.init(ThinkDifferent.java:71) at org.uecide.macosx.Platform.init(Platform.java:65) at org.uecide.Base.(Base.java:644) at org.uecide.Base.main(Base.java:185)

**Comment by majenkotech** [comment]
Apple specific stuff has now been eradicated.
