### ISSUE TITLE
ESP8266 Upload does not work

### ISSUE THREAD

**Issue by biohazardxxx** [UECIDE/UECIDE#99]
After compile the upload to ESP fails with below error. I have installed the IDE freshly and installed the ESP plugins. I think there is something wrong with the plugin because there really is no folder "tools".

Compiling...
• Compiling sketch...
• Compiling core...
‣ esp8266
‣ lwip
• Compiling libraries...
‣ Wire
‣ LiquidCrystal_I2C
• Linking sketch...
Compiling done.
Memory usage
• Program size: 222921 bytes
• Memory size: 31392 bytes
• Compilation took 0.835 seconds
Uploading firmware...
• Uploading...
Unable to start process
java.io.IOException: Cannot run program "C:\Users\xxx\AppData\Local\UECIDE\compilers\xtensa-lx106-elf/tools/esptool" (in directory "C:\Users\xxx\AppData\Local\Temp\build-3c3fe1f8-1561-4952-aad2-5b62638d1842"): CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start(Unknown Source)
    at org.uecide.Context.runSystemCommand(Context.java:867)
    at org.uecide.Context.executeCommand(Context.java:542)
    at org.uecide.Context.executeKey(Context.java:485)
    at org.uecide.Sketch.programFile(Sketch.java:3470)
    at org.uecide.Sketch.upload(Sketch.java:1650)
    at org.uecide.Editor$DefaultRunHandler.run(Editor.java:184)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 8 more
Upload Failed

**Comment by Serveurperso** [comment]
I use ESP-Link on esp8266 to flash my robot with 1 click from my website here :

esp8266 is very tricky to get working reliably.

I use a very good and overpowered DC-DC converter mandatory for esp8266
I use socat to emulate a serial port and redirect to the TCP port 2323 from ESP-Link.
The server side run on NodeJS.
 
https://www.serveurperso.com/?page=robot
You can test my PIC32 autonomous robot on this page (no ads) :D
